# charts/test-app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    {{- range .Values.services }}
    - host: {{ .host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ .name }}
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        {{- range .Values.services }}
        - {{ .host }}
        {{- end }}
      secretName: {{ printf "%s-tls" .Release.Name }}
  {{- end }}
