{{- if and (eq .Values.ingress.controller "traefik") .Values.ingress.tls .Values.ingress.sslRedirect }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
